# Generated by Django 5.0 on 2024-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='from_date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='to_date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
