# Generated by Django 5.0 on 2024-02-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_from_date_cart_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='valid_date',
            field=models.BooleanField(default=False),
        ),
    ]
