# Generated by Django 5.0 on 2024-02-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_valid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='valid_date',
        ),
    ]
