# Generated by Django 5.0 on 2023-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('Products', models.IntegerField()),
            ],
        ),
    ]
