# Generated by Django 5.0 on 2023-12-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Products',
        ),
    ]
