# Generated by Django 5.0 on 2023-12-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_remove_categories_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Products',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
