# Generated by Django 5.0 on 2023-12-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Products',
        ),
    ]
