# Generated by Django 5.0 on 2023-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0009_multipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pincodePro',
            field=models.CharField(default=101010, max_length=20),
            preserve_default=False,
        ),
    ]
