# Generated by Django 5.0 on 2024-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
