# Generated by Django 5.0 on 2024-01-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_coupons_coupon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
