# Generated by Django 5.0 on 2024-01-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0017_rename_number_coupons_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='discount',
        ),
    ]
