# Generated by Django 5.0 on 2024-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0018_remove_coupons_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
