# Generated by Django 5.0 on 2024-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_coupons_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='security',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
