# Generated by Django 5.0 on 2024-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_product_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('offer_type', models.CharField(blank=True, choices=[('category', 'category'), ('product', 'product')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
