# Generated by Django 5.0 on 2024-01-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0024_remove_offers_name_remove_offers_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rentable',
            field=models.BooleanField(default=True),
        ),
    ]
