# Generated by Django 5.0 on 2024-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0025_product_rentable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
