# Generated by Django 5.0 on 2024-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_categoryoffer_productoffer_delete_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
