# Generated by Django 5.0 on 2024-01-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0028_categoryoffer_is_active_productoffer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer_price',
            new_name='discounted_price',
        ),
    ]
