# Generated by Django 5.0 on 2024-01-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='provider_details',
        ),
    ]
