# Generated by Django 5.0 on 2024-01-14 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='provider_details',
            new_name='provider_credentials',
        ),
    ]
