# Generated by Django 5.0 on 2024-01-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_rename_provider_details_provider_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider_credentials',
            old_name='provier',
            new_name='provider',
        ),
    ]
