# Generated by Django 5.0 on 2024-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_rename_provier_provider_credentials_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_credentials',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
    ]
