# Generated by Django 5.0 on 2024-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_alter_provider_credentials_pan_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_credentials',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/provider/'),
        ),
    ]
