# Generated by Django 5.0 on 2024-01-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('Taken', 'Taken'), ('Shipped', 'shipped'), ('delivered', 'delivered'), ('rental_period', 'rental_period'), ('returned', 'returned')], default='confirmed', max_length=20),
        ),
    ]
