# Generated by Django 5.0 on 2024-01-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_status_delete_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('Taken', 'Taken'), ('Shipped', 'shipped'), ('delivered', 'delivered'), ('rental_period', 'rental_period'), ('returned', 'returned')], max_length=20),
        ),
    ]
