# Generated by Django 5.0 on 2024-01-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(default=None, null=True, blank=True),
            preserve_default=False,
        ),
    ]
