# Generated by Django 5.0 on 2024-01-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_date',
        ),
    ]
