# Generated by Django 5.0 on 2024-01-06 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ret_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
