# Generated by Django 5.0 on 2024-01-06 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_ret_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='del_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
