# Generated by Django 5.0 on 2024-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_total_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_charges',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
