# Generated by Django 5.0 on 2024-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_platform_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='caution_deposit',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
