# Generated by Django 5.0 on 2024-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_caution_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.PositiveBigIntegerField(default=40),
        ),
    ]
