# Generated by Django 5.0 on 2024-01-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_product_security'),
        ('order', '0018_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='adminPanel.coupons'),
        ),
    ]
