# Generated by Django 5.0 on 2024-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_delivery_charge',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_total_charges',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
