# Generated by Django 5.0 on 2024-01-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_offer_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_caution_deposit',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
