# Generated by Django 5.0 on 2024-01-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_offer_caution_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.BooleanField(default=False),
        ),
    ]
