# Generated by Django 5.0 on 2024-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_rental',
            field=models.BooleanField(default=False),
        ),
    ]
