# Generated by Django 5.0 on 2024-01-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_order_cancelled_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('Taken', 'Taken'), ('Shipped', 'shipped'), ('delivered', 'delivered'), ('rental_period', 'rental_period'), ('returned', 'returned'), ('cancelled', 'cancelled')], max_length=20),
        ),
    ]
