# Generated by Django 5.0 on 2024-01-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_choice',
            field=models.CharField(choices=[('paypal', 'paypal'), ('wallet', 'wallet')], default='paypal', max_length=20),
            preserve_default=False,
        ),
    ]
