# Generated by Django 5.0 on 2024-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_payment_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('Taken', 'Taken'), ('Shipped', 'shipped'), ('delivered', 'delivered'), ('rental_period', 'rental_period'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('completed', 'completed')], max_length=20),
        ),
    ]
