# Generated by Django 5.0 on 2024-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
