# Generated by Django 5.0 on 2024-02-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ret_date',
        ),
    ]
