# Generated by Django 5.0 on 2024-02-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_remove_order_ret_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='del_date',
        ),
    ]
