# Generated by Django 5.0 on 2024-02-02 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_order_del_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_date',
            field=models.DateField(default=datetime.date(2022, 2, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='to_date',
            field=models.DateField(default=datetime.date(2022, 2, 3)),
            preserve_default=False,
        ),
    ]
