# Generated by Django 5.0 on 2024-02-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_order_from_date_order_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
