# Generated by Django 5.0 on 2024-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_remove_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
