# Generated by Django 5.0 on 2023-12-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAddress',
        ),
    ]
