# Generated by Django 5.0 on 2024-01-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_useraddress_addresstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
